/*
Enter your query below.
Please append a semicolon ";" at the end of the query
*/

SELECT C.CATEGORY, C.PRODUCT_ID, C.DISCOUNT
FROM PRODUCT C
JOIN (SELECT A.CATEGORY, MIN(PRODUCT_ID) AS ID
    FROM PRODUCT A
    JOIN (SELECT CATEGORY, MAX(DISCOUNT) AS MAXIMUM
        FROM PRODUCT
        GROUP BY CATEGORY
        ORDER BY MAX(DISCOUNT) DESC) B
    ON A.CATEGORY = B.CATEGORY
    WHERE A.DISCOUNT = B.MAXIMUM
    GROUP BY CATEGORY) D
ON C.PRODUCT_ID = D.ID;
